# Generated by Django 3.1.1 on 2020-09-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20200929_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
    ]
